name: Pull Request Checks
on:
  pull_request:
    branches:
      - development
    paths:
      - "**/*.ps1"

jobs:
  unit-test:
    name: Unit testing
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup PowerShell
        uses: microsoft/setup-powershell@v1.0.0

      - name: Perform a Pester test
        shell: pwsh
        run: Invoke-Pester
