name: Pull Request Checks
on:
  pull_request:
    branches:
      - main
    paths:
      - "**.ps1"
      - "**.psm1"
      - "**.psd1"
      - "**.yml"

jobs:
  unit-test:
    name: Unit testing
    runs-on: [ubuntu-latest]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Perform a Pester test
        shell: pwsh
        run: Invoke-Pester
